# Generated by Django 5.2.3 on 2025-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_score',
            name='resume',
            field=models.FileField(default=1, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume_score',
            name='score',
            field=models.FloatField(),
        ),
    ]
