# Generated by Django 5.2.3 on 2025-07-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atsapp', '0002_resume_score_resume_alter_resume_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
